#ifndef __NirvanaEditor_SpriteLayer_ChangeTilesetWarning_Dialog__
#define __NirvanaEditor_SpriteLayer_ChangeTilesetWarning_Dialog__

/**
@file
Subclass of SpriteLayer_ChangeTilesetWarning_Dialog, which is generated by wxFormBuilder.
*/

#include "NirvanaBase.h"

//// end generated include

/** Implementing SpriteLayer_ChangeTilesetWarning_Dialog */
class NirvanaEditor_SpriteLayer_ChangeTilesetWarning_Dialog : public SpriteLayer_ChangeTilesetWarning_Dialog
{
	protected:
		// Handlers for SpriteLayer_ChangeTilesetWarning_Dialog events.
		void OnContinue( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		/** Constructor */
		NirvanaEditor_SpriteLayer_ChangeTilesetWarning_Dialog( wxWindow* parent );
	//// end generated class members

	bool continue_flag;

};

#endif // __NirvanaEditor_SpriteLayer_ChangeTilesetWarning_Dialog__
