#ifndef __NirvanaEditor_SetCamera_Dialog__
#define __NirvanaEditor_SetCamera_Dialog__

/**
@file
Subclass of SetCamera_Dialog, which is generated by wxFormBuilder.
*/

#include "NirvanaBase.h"

//// end generated include

/** Implementing SetCamera_Dialog */
class NirvanaEditor_SetCamera_Dialog : public SetCamera_Dialog
{
	protected:
		// Handlers for SetCamera_Dialog events.
		void OnCancel( wxCommandEvent& event );
		void OnSet( wxCommandEvent& event );
	public:
		int offset_x;
		int offset_y;

		bool set_flag = false;

		void initOffset(int x, int y);

		/** Constructor */
		NirvanaEditor_SetCamera_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __NirvanaEditor_SetCamera_Dialog__
