#ifndef __NirvanaEditor_NewTileset_Dialog__
#define __NirvanaEditor_NewTileset_Dialog__

/**
@file
Subclass of NewTileset_Dialog, which is generated by wxFormBuilder.
*/

#include "NirvanaBase.h"
#include "wx/arrstr.h"

//// end generated include

/** Implementing NewTileset_Dialog */
class NirvanaEditor_NewTileset_Dialog : public NewTileset_Dialog
{
	protected:
		// Handlers for NewSprite_Dialog events.
		void OnSearch( wxCommandEvent& event );
		void OnCreate( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		wxString id_name;
		int frame_width;
		int frame_height;
		wxArrayString files;
		wxString selected_file;
		bool create_flag;

		void refresh_list();

		/** Constructor */
		NirvanaEditor_NewTileset_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __NirvanaEditor_NewTileset_Dialog__
