#ifndef __NirvanaEditor_NewProject_Dialog__
#define __NirvanaEditor_NewProject_Dialog__

/**
@file
Subclass of NewProject_Dialog, which is generated by wxFormBuilder.
*/

#include "NirvanaBase.h"

//// end generated include

/** Implementing NewProject_Dialog */
class NirvanaEditor_NewProject_Dialog : public NewProject_Dialog
{
	protected:
		// Handlers for NewProject_Dialog events.
		void OnCreate( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		bool create_flag;
		wxFileName project_path;
		wxString project_name;

		/** Constructor */
		NirvanaEditor_NewProject_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __NirvanaEditor_NewProject_Dialog__
