#ifndef __NirvanaEditor_DeleteStage_Dialog__
#define __NirvanaEditor_DeleteStage_Dialog__

/**
@file
Subclass of DeleteStage_Dialog, which is generated by wxFormBuilder.
*/

#include "NirvanaBase.h"

//// end generated include

/** Implementing DeleteStage_Dialog */
class NirvanaEditor_DeleteStage_Dialog : public DeleteStage_Dialog
{
	protected:
		// Virtual event handlers, override them in your derived class
		void OnDelete( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );

	public:
		bool delete_flag;

		void setStageName(wxString stage_name);

		/** Constructor */
		NirvanaEditor_DeleteStage_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __NirvanaEditor_DeleteStage_Dialog__
