#ifndef __NirvanaEditor_SetSpriteSheet_Dialog__
#define __NirvanaEditor_SetSpriteSheet_Dialog__

/**
@file
Subclass of SetSpriteSheet_Dialog, which is generated by wxFormBuilder.
*/

#include "NirvanaBase.h"
#include "Nirvana_Project.h"
#include <wx/arrstr.h>

//// end generated include

/** Implementing SetSpriteSheet_Dialog */
class NirvanaEditor_SetSpriteSheet_Dialog : public SetSpriteSheet_Dialog
{
	protected:
		// Handlers for SetSpriteSheet_Dialog events.
		void OnSearch( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
		void OnCreate( wxCommandEvent& event );
	public:
		wxArrayString files;
		wxString selected_file;

		Nirvana_Project* project = NULL;

		bool create_flag;

		void refresh_list();

		/** Constructor */
		NirvanaEditor_SetSpriteSheet_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __NirvanaEditor_SetSpriteSheet_Dialog__
