#ifndef __NirvanaEditor_NewLayer_Dialog__
#define __NirvanaEditor_NewLayer_Dialog__

/**
@file
Subclass of NewLayer_Dialog, which is generated by wxFormBuilder.
*/

#include "NirvanaBase.h"
#include <wx/arrstr.h>

//// end generated include

/** Implementing NewLayer_Dialog */
class NirvanaEditor_NewLayer_Dialog : public NewLayer_Dialog
{
	protected:
		// Handlers for NewLayer_Dialog events.
		void OnCreate( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
		void OnLayerTypeSelect( wxCommandEvent& event );
		void OnSearch( wxCommandEvent& event );

	public:
		bool create_flag;

		wxArrayString layer_type_list;
		int selected_type;

		wxArrayString tileset_list;
		wxString selected_tileset;

		wxString layer_name;

		void refresh_list();

		/** Constructor */
		NirvanaEditor_NewLayer_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __NirvanaEditor_NewLayer_Dialog__
