#ifndef __NirvanaEditor_SpriteLayer_SelectTileset_Dialog__
#define __NirvanaEditor_SpriteLayer_SelectTileset_Dialog__

/**
@file
Subclass of SpriteLayer_SelectTileset_Dialog, which is generated by wxFormBuilder.
*/

#include "NirvanaBase.h"
#include "Nirvana_Project.h"
#include <wx/arrstr.h>

//// end generated include

/** Implementing SpriteLayer_SelectTileset_Dialog */
class NirvanaEditor_SpriteLayer_SelectTileset_Dialog : public SpriteLayer_SelectTileset_Dialog
{
	protected:
		// Handlers for SpriteLayer_SelectTileset_Dialog events.
		void OnSearch( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
		void OnSelect( wxCommandEvent& event );
	public:
		/** Constructor */
		NirvanaEditor_SpriteLayer_SelectTileset_Dialog( wxWindow* parent );
	//// end generated class members

        bool select_flag;

		int stage_index = -1;

		wxArrayString layer_type_list;
		int selected_type;

		wxArrayString tileset_list;
		wxString selected_tileset;

		Nirvana_Project* project = NULL;

		wxString layer_name;

		void refresh_list();

};

#endif // __NirvanaEditor_SpriteLayer_SelectTileset_Dialog__
