#ifndef __NirvanaEditor_AddSpriteInstance_Dialog__
#define __NirvanaEditor_AddSpriteInstance_Dialog__

/**
@file
Subclass of AddSpriteInstance_Dialog, which is generated by wxFormBuilder.
*/

#include "NirvanaBase.h"

//// end generated include

/** Implementing AddSpriteInstance_Dialog */
class NirvanaEditor_AddSpriteInstance_Dialog : public AddSpriteInstance_Dialog
{
	protected:
		// Handlers for AddSpriteInstance_Dialog events.
		void OnSearch( wxCommandEvent& event );
		void OnCreate( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		wxString id_name;
		wxArrayString base_sprites;
		wxString selected_base;
		bool create_flag;

		void refresh_list();

		/** Constructor */
		NirvanaEditor_AddSpriteInstance_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __NirvanaEditor_AddSpriteInstance_Dialog__
