#ifndef __NirvanaEditor_SpriteSortSetting_Dialog__
#define __NirvanaEditor_SpriteSortSetting_Dialog__

/**
@file
Subclass of SpriteSortSetting_Dialog, which is generated by wxFormBuilder.
*/

#include "NirvanaBase.h"

//// end generated include

/** Implementing SpriteSortSetting_Dialog */
class NirvanaEditor_SpriteSortSetting_Dialog : public SpriteSortSetting_Dialog
{
	protected:
		// Handlers for SpriteSortSetting_Dialog events.
		void OnCancel( wxCommandEvent& event );
		void OnSet( wxCommandEvent& event );
	public:
		/** Constructor */
		NirvanaEditor_SpriteSortSetting_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __NirvanaEditor_SpriteSortSetting_Dialog__
