#ifndef __NirvanaEditor_MainFrame__
#define __NirvanaEditor_MainFrame__

/**
@file
Subclass of Nirvana_MainFrame, which is generated by wxFormBuilder.
*/

#include "NirvanaBase.h"
#include "wxIrrlicht.h"
#include "Nirvana_SpriteAnimation.h"
#include "Nirvana_TileAnimation.h"
#include "Nirvana_Project.h"

#include <wx/arrstr.h>

//// end generated include

/** Implementing Nirvana_MainFrame */
class NirvanaEditor_MainFrame : public Nirvana_MainFrame
{
	private:
		Nirvana_Project* project;

		Nirvana_SpriteEditor* sprite_editor;
		Nirvana_TileEditor* tile_editor;

		void RefreshLayerProperties();

		void UpdateSpriteEditor();

		int main_page_index = 2; //TODO: CHANGE THIS AFTER TESTING IS DONE

	public:
		/** Constructor */
		NirvanaEditor_MainFrame( wxWindow* parent );
	//// end generated class members

		wxArrayString getDirFileList(wxString dir_path, wxString wildcard = _(""));

	protected:
		void OnMainTabChanged( wxAuiNotebookEvent& event );

		void OnTestButtonClick( wxCommandEvent& event );

		void OnSpriteEditor_Edit_Changed( wxAuiNotebookEvent& event );

		void OnNewSpriteClicked( wxCommandEvent& event );
		void OnSpriteEdit_SpriteIDChanged( wxCommandEvent& event );
		void OnSpriteEdit_Sprite_Selected( wxCommandEvent& event );
		void OnSpriteEdit_Animation_Selected( wxCommandEvent& event );
		void OnSpriteEdit_NewAnimation_Click( wxCommandEvent& event );
		void OnSpriteEdit_DeleteAnimation_Click( wxCommandEvent& event );
		void OnSpriteEdit_AnimationIDChanged( wxCommandEvent& event );
		void OnSpriteEdit_NumFramesChange( wxSpinEvent& event );
		void OnSpriteEdit_FPSChanged( wxSpinEvent& event );
		void OnSpriteEdit_PreviousFrame_Click( wxCommandEvent& event );
		void OnSpriteEdit_NextFrame_Click( wxCommandEvent& event );
		void OnEnterSpriteAnimationSheet( wxMouseEvent& event );
		void OnLeaveSpriteAnimationSheet( wxMouseEvent& event );
		void OnSpriteEdit_PlayPreviewClick( wxCommandEvent& event );
		void OnSpriteEdit_StopPreviewClick( wxCommandEvent& event );

		void OnSpriteEdit_ShapeSelect( wxCommandEvent& event );

		void OnSpriteEdit_Collision_Select_Click( wxCommandEvent& event );
		void OnSpriteEdit_Collision_BoxSelect_Click( wxCommandEvent& event );
		void OnSpriteEdit_Collision_Move_Click( wxCommandEvent& event );
		void OnSpriteEdit_Collision_Draw_Click( wxCommandEvent& event );

		void OnSpriteEdit_collisionBox_X_spinCtrl( wxSpinEvent& event );
		void OnSpriteEdit_collisionBox_Y_spinCtrl( wxSpinEvent& event );
		void OnSpriteEdit_collisionBox_Width_spinCtrl( wxSpinEvent& event );
		void OnSpriteEdit_collisionBox_Height_spinCtrl( wxSpinEvent& event );

		void OnSpriteAnimationSheetSize( wxSizeEvent& event );
		void OnUpdateSpriteAnimationUI( wxUpdateUIEvent& event );

		void OnProjectPropertiesTabChanged( wxAuiNotebookEvent& event );
		void OnMapEditToolsTabChanged( wxAuiNotebookEvent& event );
		void OnTileEditor_Edit_Changed( wxAuiNotebookEvent& event );


};

#endif // __NirvanaEditor_MainFrame__
