#ifndef __NirvanaEditor_DeleteSprite_Dialog__
#define __NirvanaEditor_DeleteSprite_Dialog__

/**
@file
Subclass of DeleteSprite_Dialog, which is generated by wxFormBuilder.
*/

#include "NirvanaBase.h"

//// end generated include

/** Implementing DeleteSprite_Dialog */
class NirvanaEditor_DeleteSprite_Dialog : public DeleteSprite_Dialog
{
	protected:
		// Handlers for DeleteSprite_Dialog events.
		void OnDelete( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		bool delete_flag;

		void setSpriteName(wxString stage_name);

		/** Constructor */
		NirvanaEditor_DeleteSprite_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __NirvanaEditor_DeleteSprite_Dialog__
