#ifndef __NirvanaEditor_NewStage_Dialog__
#define __NirvanaEditor_NewStage_Dialog__

/**
@file
Subclass of NewStage_Dialog, which is generated by wxFormBuilder.
*/

#include "NirvanaBase.h"
#include "Nirvana_Project.h"

//// end generated include

/** Implementing NewStage_Dialog */
class NirvanaEditor_NewStage_Dialog : public NewStage_Dialog
{
	protected:
		// Handlers for NewStage_Dialog events.
		void OnCreate( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		bool create_flag;
		wxString stage_name;
		int tile_width;
		int tile_height;
		int width_in_tiles;
		int height_in_tiles;

		Nirvana_Project* project = NULL;

		/** Constructor */
		NirvanaEditor_NewStage_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __NirvanaEditor_NewStage_Dialog__
