#ifndef __NirvanaEditor_StageProperties_Dialog__
#define __NirvanaEditor_StageProperties_Dialog__

/**
@file
Subclass of StageProperties_Dialog, which is generated by wxFormBuilder.
*/

#include "NirvanaBase.h"

//// end generated include

/** Implementing StageProperties_Dialog */
class NirvanaEditor_StageProperties_Dialog : public StageProperties_Dialog
{
	protected:
		// Handlers for StageProperties_Dialog events.
		void OnCreate( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		bool set_flag;
		int tiles_across;
		int tiles_down;
		wxString stage_name;

		void setStageProperties(wxString s_name, int t_width, int t_height, int stage_w, int stage_h);

		/** Constructor */
		NirvanaEditor_StageProperties_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __NirvanaEditor_StageProperties_Dialog__
