#ifndef __NirvanaEditor_MainFrame__
#define __NirvanaEditor_MainFrame__

/**
@file
Subclass of Nirvana_MainFrame, which is generated by wxFormBuilder.
*/

#include "NirvanaBase.h"
#include "wxIrrlicht.h"
#include "Nirvana_SpriteAnimation.h"
#include "Nirvana_TileAnimation.h"
#include "Nirvana_MapEditor.h"
#include "Nirvana_Project.h"

#include <wx/arrstr.h>
#include <vector>

//// end generated include

/** Implementing Nirvana_MainFrame */
class NirvanaEditor_MainFrame : public Nirvana_MainFrame
{
	private:
		Nirvana_Project* project;

		wxString default_tile_path = _("tiles");
		wxString default_sprite_path = _("sprites");
		wxString default_bkg_path = _("bkg");
		wxString default_stage_path = _("stages");

		wxTreeItemId project_root_treeItem;
		std::vector<wxTreeItemId> stage_treeItem;

		wxImageList* stage_tree_imageList;
		int stage_tree_rootImage;
		int stage_tree_stageImage;

		Nirvana_SpriteEditor* sprite_editor;
		Nirvana_TileEditor* tile_editor;
		Nirvana_MapEditor* map_editor;

		bool map_mapView_update;
		bool map_tileSelect_update;
		bool tile_sheetSelect_update;
		bool tile_frameSelect_update;
		bool tile_maskSelect_update;
		bool sprite_sheetSelect_update;
		bool sprite_frameSelect_update;
		bool sprite_collisionSelect_update;

		void UpdateSpriteEditor();

		void updateMapEditor();
		void reloadStage();

		void reloadSpriteProperties();

		void refreshCurrentLayerUI();

		void refreshCurrentShapeUI();

		void PreDialog();
		void PostDialog();

		wxFileName openFileDialog(wxString title, wxString default_wildcard, int flag);
		void newProject(wxFileName project_path, wxString project_name, bool create_flag=true);
		bool loadProject(wxFileName project_file);

		int selected_map_tool = -1;

		int main_page_index = 0; //TODO: CHANGE THIS AFTER TESTING IS DONE

		bool generateSpriteDefinitions();
		bool generateTilesets();
		bool generateStages();

	public:
		/** Constructor */
		NirvanaEditor_MainFrame( wxWindow* parent );
	//// end generated class members

		wxArrayString getDirFileList(wxString dir_path, wxString wildcard = _(""));

	protected:
		void OnMainTabChanged( wxAuiNotebookEvent& event );

		void OnNewProject( wxCommandEvent& event );
		void OnOpenProject( wxCommandEvent& event );
		void OnSaveProject( wxCommandEvent& event );
		void OnGenerate( wxCommandEvent& event );

		void OnMapSetFree( wxCommandEvent& event );
		void OnMapSetTiled( wxCommandEvent& event );

		void OnCameraToolClick( wxCommandEvent& event );

		void OnLayerComboClose( wxCommandEvent& event );
		void OnLayerComboOpen( wxCommandEvent& event );

		void OnNewStage( wxCommandEvent& event );
		void OnDeleteStage( wxCommandEvent& event );
		void OnMapEdit_StageSettingsClick( wxCommandEvent& event );
		void OnMapEdit_CopyStageClick( wxCommandEvent& event );

		void OnMapEdit_NewLayerClick( wxCommandEvent& event );
		void OnMapEdit_CopyLayerClick( wxCommandEvent& event );
		void OnMapEdit_ShowAllLayersClick( wxCommandEvent& event );
		void OnMapEdit_HideAllLayersClick( wxCommandEvent& event );

		void OnProjectItemActivated( wxTreeEvent& event );
		void OnActiveLayerSelect( wxCommandEvent& event );
		void OnLayerCheckListSelect( wxCommandEvent& event );
		void OnLayerCheckList_Visible_Toggle( wxCommandEvent& event );
		void OnMapEdit_LayerNameChange( wxCommandEvent& event );
		void OnEnterMapView( wxMouseEvent& event );
		void OnLeaveMapView( wxMouseEvent& event );
		void OnMapEdit_LayerUpClick( wxCommandEvent& event );
		void OnMapEdit_LayerDownClick( wxCommandEvent& event );
		void OnMapEdit_LayerDeleteClick( wxCommandEvent& event );
		void OnMapEdit_LayerHScroll( wxSpinDoubleEvent& event );
		void OnMapEdit_LayerVScroll( wxSpinDoubleEvent& event );
		void OnMapEdit_LayerAlpha( wxSpinEvent& event );

		void OnMapEdit_TileTool_Select( wxCommandEvent& event );
		void OnMapEdit_TileTool_BoxSelect( wxCommandEvent& event );
		void OnMapEdit_TileTool_Move( wxCommandEvent& event );
		void OnMapEdit_TileTool_SetTile( wxCommandEvent& event );
		void OnMapEdit_TileTool_CopyTile( wxCommandEvent& event );
		void OnMapEdit_TileTool_FillTile( wxCommandEvent& event );
		void OnMapEdit_TileTool_DeleteSelected( wxCommandEvent& event );
		void OnEnterMapEditTileSelect( wxMouseEvent& event );
		void OnLeaveMapEditTileSelect( wxMouseEvent& event );
		void OnUpdateMapEditTileSelect( wxUpdateUIEvent& event );

		void OnMapEdit_SpriteTool_Select( wxCommandEvent& event );
		void OnMapEdit_SpriteTool_BoxSelect( wxCommandEvent& event );
		void OnMapEdit_SpriteTool_Move( wxCommandEvent& event );
		void OnMapEdit_SpriteTool_Rotate( wxCommandEvent& event );
		void OnMapEdit_SpriteTool_Scale( wxCommandEvent& event );
		void OnMapEdit_SpriteTool_AddSprite( wxCommandEvent& event );
		void OnMapEdit_SpriteTool_DeleteSprite( wxCommandEvent& event );
		void OnMapEdit_SpriteTool_CopySprite( wxCommandEvent& event );
		void OnMapEdit_SpriteTool_CenterOnSprite( wxCommandEvent& event );
		void OnMapEdit_SpriteListSelect( wxCommandEvent& event );
		void OnMapEdit_SpritePropertyGridChanged( wxPropertyGridEvent& event );

		void OnMapEdit_ShapeTool_Select( wxCommandEvent& event );
		void OnMapEdit_ShapeTool_BoxSelect( wxCommandEvent& event );
		void OnMapEdit_ShapeTool_Move( wxCommandEvent& event );
		void OnMapEdit_ShapeTool_Draw( wxCommandEvent& event );
		void OnMapEdit_ShapeTool_NewBoxShape( wxCommandEvent& event );
		void OnMapEdit_ShapeTool_NewPolygonShape( wxCommandEvent& event );
		void OnMapEdit_ShapeTool_NewChainShape( wxCommandEvent& event );
		void OnMapEdit_ShapeTool_NewCircleShape( wxCommandEvent& event );
		void OnMapEdit_ShapeTool_DeleteShape( wxCommandEvent& event );
		void OnMapEdit_shapeListSelect( wxCommandEvent& event );

		void OnMapEdit_ShapeName( wxCommandEvent& event );
		void OnMapEdit_BoxShape_PosX( wxSpinEvent& event );
		void OnMapEdit_BoxShape_PosY( wxSpinEvent& event );
		void OnMapEdit_BoxShape_Width( wxSpinEvent& event );
		void OnMapEdit_BoxShape_Height( wxSpinEvent& event );
		void OnMapEdit_PolyShape_CellChange( wxGridEvent& event );
		void OnMapEdit_CircleShape_CenterX( wxSpinEvent& event );
		void OnMapEdit_CircleShape_CenterY( wxSpinEvent& event );
		void OnMapEdit_CircleShape_Radius( wxSpinEvent& event );

		void OnBkg_RenderType( wxCommandEvent& event );
		void OnBkg_LayerImage( wxCommandEvent& event );

		void OnMapEdit_Map_UpdateUI( wxUpdateUIEvent& event );

		void OnSpriteEditor_Edit_Changed( wxAuiNotebookEvent& event );

		void OnNewSpriteClicked( wxCommandEvent& event );
		void OnDeleteSpriteClicked( wxCommandEvent& event );
		void OnSpriteEdit_SpriteIDChanged( wxCommandEvent& event );
		void OnSpriteEdit_Sprite_Selected( wxCommandEvent& event );
		void OnSpriteEdit_Animation_Selected( wxCommandEvent& event );
		void OnSpriteEdit_NewAnimation_Click( wxCommandEvent& event );
		void OnSpriteEdit_DeleteAnimation_Click( wxCommandEvent& event );
		void OnSpriteEdit_AnimationIDChanged( wxCommandEvent& event );
		void OnSpriteEdit_NumFramesChange( wxSpinEvent& event );
		void OnSpriteEdit_FPSChanged( wxSpinEvent& event );
		void OnSpriteEdit_PreviousFrame_Click( wxCommandEvent& event );
		void OnSpriteEdit_NextFrame_Click( wxCommandEvent& event );
		void OnEnterSpriteAnimationSheet( wxMouseEvent& event );
		void OnLeaveSpriteAnimationSheet( wxMouseEvent& event );
		void OnSpriteEdit_PlayPreviewClick( wxCommandEvent& event );
		void OnSpriteEdit_StopPreviewClick( wxCommandEvent& event );

		void OnSpriteEdit_ShapeSelect( wxCommandEvent& event );

		void OnSpriteEdit_Collision_Select_Click( wxCommandEvent& event );
		void OnSpriteEdit_Collision_BoxSelect_Click( wxCommandEvent& event );
		void OnSpriteEdit_Collision_Move_Click( wxCommandEvent& event );
		void OnSpriteEdit_Collision_Draw_Click( wxCommandEvent& event );

		void OnSpriteEdit_collisionBox_X_spinCtrl( wxSpinEvent& event );
		void OnSpriteEdit_collisionBox_Y_spinCtrl( wxSpinEvent& event );
		void OnSpriteEdit_collisionBox_Width_spinCtrl( wxSpinEvent& event );
		void OnSpriteEdit_collisionBox_Height_spinCtrl( wxSpinEvent& event );

		void OnSpriteEdit_collisionCircle_X_spinCtrl( wxSpinEvent& event );
		void OnSpriteEdit_collisionCircle_Y_spinCtrl( wxSpinEvent& event );
		void OnSpriteEdit_collisionCircle_Radius_spinCtrl( wxSpinEvent& event );

		void OnSpriteEdit_collisionPolygon_gridCellChange( wxGridEvent& event );

		void OnSpriteAnimationSheetSize( wxSizeEvent& event );
		void OnUpdateSpriteAnimationUI( wxUpdateUIEvent& event );

		void OnNewTilesetClick( wxCommandEvent& event );
		void OnDeleteTilesetClick( wxCommandEvent& event );
		void OnTileEdit_TileIDChanged( wxCommandEvent& event );
		void OnTileEditor_Edit_Changed( wxAuiNotebookEvent& event );
		void OnTileEdit_TilesetSelected( wxCommandEvent& event );
		void OnEnterTileAnimationSheet( wxMouseEvent& event );
		void OnLeaveTileAnimationSheet( wxMouseEvent& event );
		void OnTileEdit_NumFramesChange( wxSpinEvent& event );
		void OnTileEdit_FPSChanged( wxSpinEvent& event );
		void OnTileEdit_PreviousFrame_Click( wxCommandEvent& event );
		void OnTileEdit_NextFrame_Click( wxCommandEvent& event );

		void OnTileEdit_TileSelect_Tool( wxCommandEvent& event );
		void OnTileEdit_TileAnimation_Tool( wxCommandEvent& event );

		void OnTileEdit_PlayPreviewClick( wxCommandEvent& event );
		void OnTileEdit_StopPreviewClick( wxCommandEvent& event );

		void OnUpdateTileAnimationUI( wxUpdateUIEvent& event );

		void OnTileEdit_newMaskClick( wxCommandEvent& event );
		void OnTileEdit_deleteMaskClick( wxCommandEvent& event );
		void OnTileEdit_maskIDChanged( wxCommandEvent& event );
		void OnEnterTileMaskSheet( wxMouseEvent& event );
		void OnLeaveTileMaskSheet( wxMouseEvent& event );
		void OnTileEdit_maskSelected( wxCommandEvent& event );

		void OnUpdateTileMaskUI( wxUpdateUIEvent& event );

		void OnProjectPropertiesTabChanged( wxAuiNotebookEvent& event );
		void OnMapEditToolsTabChanged( wxAuiNotebookEvent& event );

};

#endif // __NirvanaEditor_MainFrame__
